virtualService:
  # internal 
  #host: "<service_name>.<service_namespace>.svc.cluster.local"
  # external cloudflare
  #host: "bookinfo.kapoozi.com"
  # wildcard host
  host: "'*'"

service:
  name: product-page-svc
  port: 9080

productionDeployment:
  replicaCount: 2
  weight: 100
  image:
    repository: ably77/bookinfo-canary
    tag: 1
    pullPolicy: IfNotPresent


canaryDeployment:
  replicaCount: 0
  weight: 0
  image:
    repository: ably77/bookinfo-canary
    tag: 2
    pullPolicy: IfNotPresent



